version: '3.4'

services:
  roshambo_account_postgres:
    container_name: roshambo_account_postgres
    environment:
      - POSTGRES_DB=roshambo
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    image: postgres:12-alpine
    ports:
      - 5410:5432
    restart: unless-stopped
    volumes:
      - roshambo_account_postgres:/var/lib/postgresql/data

  roshambo_profile_postgres:
    container_name: roshambo_profile_postgres
    environment:
      - POSTGRES_DB=roshambo
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    image: postgres:12-alpine
    ports:
      - 5430:5432
    restart: unless-stopped
    volumes:
      - roshambo_profile_postgres:/var/lib/postgresql/data

  roshambo_stat_postgres:
    container_name: roshambo_stat_postgres
    environment:
      - POSTGRES_DB=roshambo
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    image: postgres:12-alpine
    ports:
      - 5440:5432
    restart: unless-stopped
    volumes:
      - roshambo_stat_postgres:/var/lib/postgresql/data

  # redis service for environment variables
  roshambo_redis:
    container_name: roshambo_redis
    command: ["redis-server", "--appendonly", "yes"]
    image: redis:latest
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - roshambo_redis:/data

volumes:
  roshambo_account_postgres:
  roshambo_profile_postgres:
  roshambo_stat_postgres:
  roshambo_redis:
